### ISSUE TITLE
skywalking集成arthas，ui部署有问题

### ISSUE THREAD

**Issue by fruitfish** [weixiang1862/skywalking-x-arthas#2]
我的skywalking版本是9.2.0，使用二进制文件部署的。jdk版本是 11.0.19
参考的方式是  `https://github.com/weixiang1862/skywalking-x-arthas#quick-start`  这个中的步骤。
oap-server正常启动了。
但是使用skywalking-x-arthas项目中的 dist/skywalking-webapp.jar 前端部署包，启动异常了。报错信息如下：
```
Exception in thread "main" org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:214)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:172)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:167)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:122)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1204)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:320)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:212)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:156)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486)
        at org.apache.skywalking.oap.server.webapp.ApplicationStartUp.main(ApplicationStartUp.java:44)
Caused by: java.io.IOException: Stream closed
        at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:75)
        at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:163)
        at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:179)
        ... 14 more
```
请问一下，这个需要怎么处理？

**Comment by fruitfish** [comment]
oap-server 启动好像也有问题。
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/19407667/92399f93-50bf-43da-9a37-43ce9c3e2d58)

配了以下的配置后，oap-server也起不来了，之前忘记配了
```
cat << EOF >>${your_oap_server_home}/config/application.yml
> arthas-controller:
>   selector: default
>   default:
> EOF
```

**Comment by weixiang1862** [comment]
这个插件是基于skywalking9.6、skywalking-agent9.1开发的，skywalking9.2与9.6代码变化挺多的，这个插件不兼容9.2

**Comment by fruitfish** [comment]
> 这个插件是基于skywalking9.6、skywalking-agent9.1开发的，skywalking9.2与9.6代码变化挺多的，这个插件不兼容9.2

好的，那我先升级一下skywalking版本到9.6.0试试。我看了下Java Agent的最新版本好像是v9.0.0吧。

还有在请问一下，这个插件也可以应用于k8s部署的skywalking吗？

**Comment by weixiang1862** [comment]
是的，可以用于k8s部署
